config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :profiles

  
  resources :profiles do
    resources :reviews
  end


  resources :adds
  resources :motors


  get :search, controller: :searchresults
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'motors#index'
end

app/models/profile.rb
class Profile < ApplicationRecord
	extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
		authentication_keys: [:email]


  #has_many :motors
  has_many :adds
  has_many :reviews

	def average_rating
	 self.reviews.any? ? self.reviews.average(:rating).round(1) : 0
	end











end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_profile!, :except => [:index, :show]
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @review = Review.new
    @reviews = Review.where(profile_id: params[:id])
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :email)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.first_name %></td>
        <td><%= profile.last_name %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form', profile: @profile %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<div class="row">
       <div class="col-md-4">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="http://via.placeholder.com/350x350" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">User Name</p>
          </div>
        </div>
       </div>
       <div class="col-md-8">
         <div class="card text-center">
           <div class="card-header">
             <ul class="nav nav-pills card-header-pills">
               <li class="nav-item">
                 <a class="nav-link active" href="#">Additional Details</a>
               </li>
             </ul>
           </div>
           <div class="card-body">
             <h5 class="card-title">User additional details</h5>
             <p class="card-text">More details about the car.</p>
             <a href="#" class="btn btn-primary">More Details</a>
           </div>
         </div>
       </div>
     </div>
     <div class="row">
     			<div class="col-sm-4">
     				<div class="rating-block">
     					<h4>Average user rating</h4>
     					<h2 class="bold padding-bottom-7"><%= @profile.average_rating %><small> / 5</small></h2>
              <div id="average_rating" data-score=<%= @profile.average_rating %>></div>
     				</div>
     			</div>
     			<div class="col-sm-4">
     				<h4>Rating breakdown</h4>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">5 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="5" style="width: 1000%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">1</div>
     				</div>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">4 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="5" style="width: 80%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">1</div>
     				</div>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">3 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="5" style="width: 60%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">0</div>
     				</div>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">2 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="5" style="width: 40%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">0</div>
     				</div>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">1 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="5" style="width: 20%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">0</div>
     				</div>
     			</div>
     		</div>

     		<div class="row">
     			<div class="col-sm-12">
     				<hr/>
     				<div class="review-block">
              <%= render "reviews/profile_reviews" %>
     				</div>
     			</div>
     		</div>
        <div class="row">
          <div class="col-sm-12">
            <% if profile_signed_in? %>
              <%= render "reviews/form", :review => @review %>
            <% else %>
              <p  style="margin-bottom:200px;">
                <em>
                  login to submit a review
                  <%= link_to "Login", new_profile_session_path %>
                </em>
              </p>
            <% end %>
          </div>
        </div>

        <script>
          $('#average_rating').raty({
            path: '/assets/',
            half: true,
            readOnly: true,
            score: function () {
              return $(this).attr('data-score');
            }
          });
        </script>