config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :profiles

  
  resources :profiles do
    resources :reviews
  end


  resources :adds
  resources :motors


  get :search, controller: :searchresults
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'motors#index'
end

app/models/motor.rb
class Motor < ApplicationRecord
	#belongs_to :profiles
end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
  before_action :authenticate_profile!
  before_action :set_motor, only: [:show, :edit, :update, :destroy]

  # GET /motors
  # GET /motors.json
  def index
    @motors = Motor.all
  end

  # GET /motors/1
  # GET /motors/1.json
  def show
  end

  # GET /motors/new
  def new
    @motor = Motor.new
  end

  # GET /motors/1/edit
  def edit
  end

  # POST /motors
  # POST /motors.json
  def create
    @motor = Motor.new(motor_params)

    respond_to do |format|
      if @motor.save
        format.html { redirect_to @motor, notice: 'Motor was successfully created.' }
        format.json { render :show, status: :created, location: @motor }
      else
        format.html { render :new }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motors/1
  # PATCH/PUT /motors/1.json
  def update
    respond_to do |format|
      if @motor.update(motor_params)
        format.html { redirect_to @motor, notice: 'Motor was successfully updated.' }
        format.json { render :show, status: :ok, location: @motor }
      else
        format.html { render :edit }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motors/1
  # DELETE /motors/1.json
  def destroy
    @motor.destroy
    respond_to do |format|
      format.html { redirect_to motors_url, notice: 'Motor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motor
      @motor = Motor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motor_params
       params.require(:motor).permit(:title, :slug, :local_area, :town )
      
    end
end

app/helpers/motors_helper.rb
module MotorsHelper
end

app/views/motors/_form.html.erb
<%= simple_form_for(@motor) do |f| %>
  <% if motor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(motor.errors.count, "error") %> prohibited this motor from being saved:</h2>

      <ul>
      <% motor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :town %>
    <%= f.input :local_area %>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/motors/edit.html.erb
<h1>Editing Motor</h1>

<%= render 'form', motor: @motor %>

<%= link_to 'Show', @motor %> |
<%= link_to 'Back', motors_path %>

app/views/motors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>motors</h1>

<%= render 'layouts/searchform' %>

<br>


<table>
  <thead>
    <tr>
      <th>Title</th>
  
      <th>Town</th>
      <th>Local area</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motors.each do |motor| %>
      <tr>
        <td><%= motor.title %></td>
        <td><%= motor.town %></td>
        <td><%= motor.local_area %></td>
        <td><%= link_to 'Show', motor %></td>
        <td><%= link_to 'Edit', edit_motor_path(motor) %></td>
        <td><%= link_to 'Destroy', motor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motor', new_motor_path %>

app/views/motors/new.html.erb
<h1>New Motor</h1>

<%= render 'form', motor: @motor %>

<%= link_to 'Back', motors_path %>

app/views/motors/show.html.erb
<p id="notice"><%= notice %></p>

<%= render 'layouts/searchform' %>


   <div class="row">
       <div class="col-md-4">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="http://via.placeholder.com/350x350" alt="Card image cap">
          <div class="card-body">
            <p class="card-text">Motor Name</p>
          </div>
        </div>
       </div>
       <div class="col-md-8">
         <div class="card text-center">
           <div class="card-header">
             <ul class="nav nav-pills card-header-pills">
               <li class="nav-item">
                 <a class="nav-link active" href="#">Additional Details</a>
               </li>
             </ul>
           </div>
           <div class="card-body">
             <h5 class="card-title">Car Brand Name</h5>
             <p class="card-text">Some details about the car.</p>
             <a href="#" class="btn btn-primary">More Details</a>
           </div>
         </div>
       </div>
     </div>
     <div class="row">
     			<div class="col-sm-4">
     				<div class="rating-block">
     					<h4>Average user rating</h4>
     					<h2 class="bold padding-bottom-7">4.3 <small>/ 5</small></h2>
     					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
     					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     					</button>
     					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
     					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     					</button>
     					<button type="button" class="btn btn-warning btn-sm" aria-label="Left Align">
     					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     					</button>
     					<button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
     					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     					</button>
     					<button type="button" class="btn btn-default btn-grey btn-sm" aria-label="Left Align">
     					  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     					</button>
     				</div>
     			</div>
     			<div class="col-sm-4">
     				<h4>Rating breakdown</h4>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">5 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="5" aria-valuemin="0" aria-valuemax="5" style="width: 1000%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">1</div>
     				</div>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">4 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="4" aria-valuemin="0" aria-valuemax="5" style="width: 80%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">1</div>
     				</div>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">3 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="3" aria-valuemin="0" aria-valuemax="5" style="width: 60%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">0</div>
     				</div>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">2 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="5" style="width: 40%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">0</div>
     				</div>
     				<div class="pull-left">
     					<div class="pull-left" style="width:35px; line-height:1;">
     						<div style="height:9px; margin:5px 0;">1 <span class="glyphicon glyphicon-star"></span></div>
     					</div>
     					<div class="pull-left" style="width:180px;">
     						<div class="progress" style="height:9px; margin:8px 0;">
     						  <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="1" aria-valuemin="0" aria-valuemax="5" style="width: 20%">
     							<span class="sr-only">80% Complete (danger)</span>
     						  </div>
     						</div>
     					</div>
     					<div class="pull-right" style="margin-left:10px;">0</div>
     				</div>
     			</div>		
     		</div>			
		
     		<div class="row">
     			<div class="col-sm-12">
     				<hr/>
     				<div class="review-block">
     					<div class="row">
     						<div class="col-sm-3">
     							<img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image" class="img-rounded">
     							<div class="review-block-name"><a href="#">nktailor</a></div>
     							<div class="review-block-date">January 29, 2016<br/>1 day ago</div>
     						</div>
     						<div class="col-sm-9">
     							<div class="review-block-rate">
     								<button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     							</div>
     							<div class="review-block-title">this was nice in buy</div>
     							<div class="review-block-description">this was nice in buy. this was nice in buy. this was nice in buy. this was nice in buy this was nice in buy this was nice in buy this was nice in buy this was nice in buy</div>
     						</div>
     					</div>
     					<hr/>
     					<div class="row">
     						<div class="col-sm-3">
     							<img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image" class="img-rounded">
     							<div class="review-block-name"><a href="#">nktailor</a></div>
     							<div class="review-block-date">January 29, 2016<br/>1 day ago</div>
     						</div>
     						<div class="col-sm-9">
     							<div class="review-block-rate">
     								<button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     							</div>
     							<div class="review-block-title">this was nice in buy</div>
     							<div class="review-block-description">this was nice in buy. this was nice in buy. this was nice in buy. this was nice in buy this was nice in buy this was nice in buy this was nice in buy this was nice in buy</div>
     						</div>
     					</div>
     					<hr/>
     					<div class="row">
     						<div class="col-sm-3">
     							<img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image" class="img-rounded">
     							<div class="review-block-name"><a href="#">nktailor</a></div>
     							<div class="review-block-date">January 29, 2016<br/>1 day ago</div>
     						</div>
     						<div class="col-sm-9">
     							<div class="review-block-rate">
     								<button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-warning btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     								<button type="button" class="btn btn-default btn-grey btn-xs" aria-label="Left Align">
     								  <span class="glyphicon glyphicon-star" aria-hidden="true"></span>
     								</button>
     							</div>
     							<div class="review-block-title">this was nice in buy</div>
     							<div class="review-block-description">this was nice in buy. this was nice in buy. this was nice in buy. this was nice in buy this was nice in buy this was nice in buy this was nice in buy this was nice in buy</div>
     						</div>
     					</div>
     				</div>
     			</div>
     		</div>
        <div class="row">
          <hr/>
          <div class="col-sm-12">
            <div class="form-group">
              <label for="exampleFormControlTextarea1">Add Your Reviews</label>
              <textarea class="form-control" id="exampleFormControlTextarea1" rows="5"></textarea>
            </div>
            <button type="button" class="btn btn-primary btn-block">Submit</button>
          </div>
        </div>
  
 
  