config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  devise_for :profiles

  
  resources :profiles do
    resources :reviews
  end


  resources :adds
  resources :motors


  get :search, controller: :searchresults
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'motors#index'
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    # @profile = Profile.find(params[:id])
    @profile = Profile.find(params[:id])
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @profile = Profile.find(params[:profile_id])
    @review = @profile.reviews.build(review_params)

    respond_to do |format|
      if @review.save
        @reviews = @profile.reviews
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
        format.js
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :reviewer_id)
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for([@profile, review], remote: true, :defaults => { :input_html => { :class => "form-control"}}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-group">
    <label for="exampleFormControlTextarea1">Add Your Reviews</label>
    <div style="margin-bottom: 10px;" id='star-rating'></div>
    <%= f.input :comment, :input_html => {rows: "5"} %>
    <%= f.hidden_field :reviewer_id, :value => current_profile.id %>
  </div>
  <%= f.button :submit, class: "btn btn-primary btn-block"  %>

 <% end %>


  <script>
  $('#star-rating').raty({
      path: '/assets',
      scoreName: 'review[rating]'
  });
  </script>

app/views/reviews/_profile_reviews.html.erb
<% @reviews.each do |review| %>
  <div class="row">
    <div class="col-sm-3">
      <img src="http://dummyimage.com/60x60/666/ffffff&text=No+Image" class="img-rounded">
      <div class="review-block-name">
        <% unless review.reviewer_id.nil? %>
        <a href="#"><%= Profile.find(review.reviewer_id).first_name %></a>
        <% end %>
      </div>
      <div class="review-block-date"><%= review.created_at.strftime("%B %d, %Y") %><br/><%= time_ago_in_words(review.created_at) %>
        ago</div>
    </div>
    <div class="col-sm-9">
      <div class="review-block-rate">
        <div class="star-rating" data-score=<%= review.rating %>></div>
      </div>
      <div class="review-block-description"><%= review.comment %></div>
    </div>
  </div>
  <hr/>
<% end %>

<script>
  $('.star-rating').raty({
    path: '/assets/',
    readOnly: true,
    score: function () {
      return $(this).attr('data-score');
    }
  });
</script>

app/views/reviews/create.js.erb
$(".review-block").html("<%= j(render :partial=> 'reviews/profile_reviews') %>");
$("#review_comment").val('');
$('#star-rating').raty('set', { option: 0 });

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>